"""
Team attack/defense parameters calibrated realistically for each league.
Parameters are on log scale (Dixon-Coles convention).
home_adv: log home advantage factor per league.
market_margin: typical bookmaker overround (e.g. 0.05 = 5%).
"""

LEAGUES = {
    "premier_league": {
        "name": "Premier League",
        "country": "England",
        "home_adv": 0.25,
        "market_margin": 0.05,
        "avg_goals": 2.7,
        "teams": {
            "Manchester City":    {"attack": 0.82, "defense": -0.65},
            "Arsenal":            {"attack": 0.71, "defense": -0.58},
            "Liverpool":          {"attack": 0.75, "defense": -0.52},
            "Chelsea":            {"attack": 0.55, "defense": -0.40},
            "Tottenham":          {"attack": 0.52, "defense": -0.28},
            "Aston Villa":        {"attack": 0.48, "defense": -0.33},
            "Newcastle":          {"attack": 0.44, "defense": -0.38},
            "Manchester United":  {"attack": 0.38, "defense": -0.18},
            "West Ham":           {"attack": 0.35, "defense": -0.20},
            "Brighton":           {"attack": 0.42, "defense": -0.30},
            "Wolves":             {"attack": 0.28, "defense": -0.22},
            "Brentford":          {"attack": 0.32, "defense": -0.15},
            "Fulham":             {"attack": 0.30, "defense": -0.25},
            "Crystal Palace":     {"attack": 0.22, "defense": -0.20},
            "Everton":            {"attack": 0.18, "defense": -0.12},
            "Nottingham Forest":  {"attack": 0.20, "defense": -0.30},
            "Bournemouth":        {"attack": 0.25, "defense": -0.10},
            "Luton":              {"attack": 0.10, "defense": -0.05},
            "Burnley":            {"attack": 0.08, "defense": -0.03},
            "Sheffield United":   {"attack": 0.05, "defense": -0.02},
        }
    },
    "la_liga": {
        "name": "La Liga",
        "country": "Spain",
        "home_adv": 0.22,
        "market_margin": 0.05,
        "avg_goals": 2.5,
        "teams": {
            "Real Madrid":        {"attack": 0.85, "defense": -0.68},
            "Barcelona":          {"attack": 0.80, "defense": -0.55},
            "Atletico Madrid":    {"attack": 0.60, "defense": -0.70},
            "Girona":             {"attack": 0.62, "defense": -0.45},
            "Athletic Bilbao":    {"attack": 0.42, "defense": -0.50},
            "Real Sociedad":      {"attack": 0.45, "defense": -0.42},
            "Real Betis":         {"attack": 0.40, "defense": -0.38},
            "Valencia":           {"attack": 0.32, "defense": -0.30},
            "Villarreal":         {"attack": 0.38, "defense": -0.35},
            "Sevilla":            {"attack": 0.35, "defense": -0.28},
            "Osasuna":            {"attack": 0.28, "defense": -0.40},
            "Celta Vigo":         {"attack": 0.30, "defense": -0.22},
            "Las Palmas":         {"attack": 0.22, "defense": -0.18},
            "Getafe":             {"attack": 0.18, "defense": -0.42},
            "Deportivo Alaves":   {"attack": 0.15, "defense": -0.20},
            "Cadiz":              {"attack": 0.12, "defense": -0.15},
            "Mallorca":           {"attack": 0.20, "defense": -0.35},
            "Rayo Vallecano":     {"attack": 0.22, "defense": -0.25},
            "Granada":            {"attack": 0.10, "defense": -0.08},
            "Almeria":            {"attack": 0.08, "defense": -0.05},
        }
    },
    "serie_a": {
        "name": "Serie A",
        "country": "Italy",
        "home_adv": 0.20,
        "market_margin": 0.05,
        "avg_goals": 2.6,
        "teams": {
            "Inter Milan":        {"attack": 0.78, "defense": -0.70},
            "AC Milan":           {"attack": 0.65, "defense": -0.55},
            "Juventus":           {"attack": 0.60, "defense": -0.62},
            "Napoli":             {"attack": 0.58, "defense": -0.45},
            "Roma":               {"attack": 0.52, "defense": -0.40},
            "Atalanta":           {"attack": 0.70, "defense": -0.42},
            "Lazio":              {"attack": 0.55, "defense": -0.38},
            "Fiorentina":         {"attack": 0.45, "defense": -0.35},
            "Bologna":            {"attack": 0.42, "defense": -0.38},
            "Torino":             {"attack": 0.35, "defense": -0.45},
            "Verona":             {"attack": 0.28, "defense": -0.22},
            "Udinese":            {"attack": 0.25, "defense": -0.28},
            "Monza":              {"attack": 0.30, "defense": -0.25},
            "Cagliari":           {"attack": 0.22, "defense": -0.18},
            "Genoa":              {"attack": 0.20, "defense": -0.20},
            "Lecce":              {"attack": 0.18, "defense": -0.15},
            "Frosinone":          {"attack": 0.15, "defense": -0.12},
            "Empoli":             {"attack": 0.20, "defense": -0.18},
            "Salernitana":        {"attack": 0.10, "defense": -0.08},
            "Sassuolo":           {"attack": 0.25, "defense": -0.20},
        }
    },
    "bundesliga": {
        "name": "Bundesliga",
        "country": "Germany",
        "home_adv": 0.28,
        "market_margin": 0.05,
        "avg_goals": 3.1,
        "teams": {
            "Bayer Leverkusen":   {"attack": 0.82, "defense": -0.62},
            "Bayern Munich":      {"attack": 0.90, "defense": -0.60},
            "Stuttgart":          {"attack": 0.62, "defense": -0.48},
            "Borussia Dortmund":  {"attack": 0.68, "defense": -0.40},
            "RB Leipzig":         {"attack": 0.65, "defense": -0.50},
            "Eintracht Frankfurt":{"attack": 0.50, "defense": -0.35},
            "Freiburg":           {"attack": 0.42, "defense": -0.48},
            "Wolfsburg":          {"attack": 0.40, "defense": -0.38},
            "Borussia Mönchengladbach":{"attack": 0.38, "defense": -0.30},
            "Werder Bremen":      {"attack": 0.35, "defense": -0.28},
            "Hoffenheim":         {"attack": 0.38, "defense": -0.32},
            "Heidenheim":         {"attack": 0.30, "defense": -0.35},
            "Augsburg":           {"attack": 0.25, "defense": -0.25},
            "Union Berlin":       {"attack": 0.28, "defense": -0.30},  
            "Bochum":             {"attack": 0.18, "defense": -0.15},
            "Mainz":              {"attack": 0.32, "defense": -0.28},
            "Köln":               {"attack": 0.22, "defense": -0.18},
            "Darmstadt":          {"attack": 0.12, "defense": -0.10},
        }
    },
    "ligue_1": {
        "name": "Ligue 1",
        "country": "France",
        "home_adv": 0.23,
        "market_margin": 0.05,
        "avg_goals": 2.5,
        "teams": {
            "PSG":                {"attack": 0.92, "defense": -0.65},
            "Monaco":             {"attack": 0.65, "defense": -0.48},
            "Brest":              {"attack": 0.55, "defense": -0.45},
            "Lille":              {"attack": 0.52, "defense": -0.52},
            "Nice":               {"attack": 0.48, "defense": -0.50},
            "Lyon":               {"attack": 0.50, "defense": -0.38},
            "Marseille":          {"attack": 0.55, "defense": -0.35},
            "Lens":               {"attack": 0.45, "defense": -0.42},
            "Rennes":             {"attack": 0.42, "defense": -0.35},
            "Reims":              {"attack": 0.30, "defense": -0.38},
            "Toulouse":           {"attack": 0.32, "defense": -0.30},
            "Strasbourg":         {"attack": 0.28, "defense": -0.25},
            "Nantes":             {"attack": 0.25, "defense": -0.28},
            "Montpellier":        {"attack": 0.22, "defense": -0.18},
            "Le Havre":           {"attack": 0.18, "defense": -0.20},
            "Metz":               {"attack": 0.15, "defense": -0.12},
            "Lorient":            {"attack": 0.18, "defense": -0.15},
            "Clermont":           {"attack": 0.12, "defense": -0.10},
        }
    },
}

# Fixtures are now fetched in real-time from The Odds API.
# No more hardcoded/invented matches.
FIXTURES = {}
